#pragma once
#ifndef MINIZ_EXPORT_H
#define MINIZ_EXPORT_H

// Dummy miniz_export.h to satisfy miniz 2.2.0+ which expects this file to be
// generated by its own CMake. We compile miniz statically, so MINIZ_EXPORT
// is just an empty macro.
#define MINIZ_EXPORT

#endif // MINIZ_EXPORT_H
